
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author renan
 */
public class Exercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio2
     */
    public Exercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectPedra = new javax.swing.JRadioButton();
        selectPapel = new javax.swing.JRadioButton();
        selectTesoura = new javax.swing.JRadioButton();
        lblTitulo = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectPedra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        selectPedra.setText("Pedra");

        selectPapel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        selectPapel.setText("Papel");

        selectTesoura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        selectTesoura.setText("Tesoura");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Escolha sua jogada:");

        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(selectPedra)
                        .addGap(18, 18, 18)
                        .addComponent(selectPapel)
                        .addGap(18, 18, 18)
                        .addComponent(selectTesoura))
                    .addComponent(lblTitulo))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectTesoura)
                    .addComponent(selectPapel)
                    .addComponent(selectPedra))
                .addGap(18, 18, 18)
                .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        int escolhaUsuario = -1;
        String escolhaUsuarioStr = "";
        if (selectPedra.isSelected()) {
            escolhaUsuario = 0;
            escolhaUsuarioStr = "Pedra";
        } else if (selectPapel.isSelected()) {
            escolhaUsuario = 1;
            escolhaUsuarioStr = "Papel";
        } else if (selectTesoura.isSelected()) {
            escolhaUsuario = 2;
            escolhaUsuarioStr = "Tesoura";
        }

        if (escolhaUsuario != -1) {
            int escolhaComp = escolhaComputador();
            String escolhaCompStr = "";
            switch (escolhaComp) {
                case 0:
                    escolhaCompStr = "Pedra";
                    break;
                case 1:
                    escolhaCompStr = "Papel";
                    break;
                case 2:
                    escolhaCompStr = "Tesoura";
                    break;
            }

            String vencedor = determinarVencedor(escolhaUsuario, escolhaComp);

            javax.swing.JOptionPane.showMessageDialog(this, "O vencedor é: " + vencedor
                    + "\n\nVocê escolheu: " + escolhaUsuarioStr
                    + "\nComputador escolheu: " + escolhaCompStr);

            selectPedra.setSelected(false);
            selectPapel.setSelected(false);
            selectTesoura.setSelected(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione uma opção.");
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    private int escolhaComputador() {
        Random random = new Random();
        return random.nextInt(3);
    }

    private String determinarVencedor(int escolhaUsuario, int escolhaComputador) {
        if (escolhaUsuario == escolhaComputador) {
            return "Empate";
        } else if ((escolhaUsuario == 0 && escolhaComputador == 2)
                || (escolhaUsuario == 1 && escolhaComputador == 0)
                || (escolhaUsuario == 2 && escolhaComputador == 1)) {
            return "Você";
        } else {
            return "Computador";
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton selectPapel;
    private javax.swing.JRadioButton selectPedra;
    private javax.swing.JRadioButton selectTesoura;
    // End of variables declaration//GEN-END:variables
}
